'use server'

const mockServices = [

  // Western Massages Start
  {
    id: '1',
    name: 'Therapeutic Massage',
    description: 'A therapeutic massage is used to stimulate relaxation. Therapeutic massage can be used to reduce stress, improve blood circulation, and reduce pain. There are many techniques used in a therapeutic massage including effleurage, kneading, lymphatic drainage, picking up and skin rolling.',
    minPrice: '65',
    midPrice: "95",
    maxPrice: "125",
    minDuration: 60,
    midDuration: 90,
    maxDuration: 120,
    image: "/services/Therapeutic Massage.jpg",
    category: 'Western Massage',
  },
  {
    id: '2',
    name: 'Couple Massage',
    description: 'Couples massage is a shared experience where two people receive massages at the same time, in the same room, from two different therapists. It’s a popular choice for couples, friends, or family members who want to enjoy a massage together. ',
    minPrice: '65',
    midPrice: "95",
    maxPrice: "125",
    minDuration: 60,
    midDuration: 90,
    maxDuration: 120,
    image: "/services/COUPLE MASSAGE.jpg",
    category: 'Western Massage',
  },
  {
    id: '3',
    name: 'Deep Tissue Massage/Sports',
    description: 'Deep tissue massage is a therapeutic massage technique that focuses on realigning deeper layers of muscles and connective tissue. ',
    minPrice: '65',
    midPrice: "95",
    maxPrice: "125",
    minDuration: 60,
    midDuration: 90,
    maxDuration: 120,
    image: "/services/DEEP TISSUE MASSAGE: SPORTS.jpg",
    category: 'Western Massage',
  },
  {
    id: '4',
    name: 'Head, Neck & Shoulder',
    description: 'A head, neck, and shoulder massage is a therapeutic treatment that focuses on these specific areas of the body. It is designed to relieve tension, reduce stress, and promote relaxation. ',
    minPrice: '65',
    midPrice: "95",
    maxPrice: "125",
    minDuration: 60,
    midDuration: 90,
    maxDuration: 120,
    image: "/services/HEAD, NECK & SHOULDER.jpg",
    category: 'Western Massage',
  },
  {
    id: '5',
    name: 'Balinese Massage',
    description: 'Balinese massage is a traditional Indonesian massage therapy that combines a variety of techniques including massage, acupressure, reflexology, and aromatherapy to stimulate blood circulation, ease tension, and promote relaxation.',
    minPrice: '65',
    midPrice: "95",
    maxPrice: "125",
    minDuration: 60,
    midDuration: 90,
    maxDuration: 120,
    image: "/services/BALINESE MASSAGE.jpg",
    category: 'Western Massage',
  },
  {
    id: '6',
    name: 'Lymphatic Massage',
    description: 'Lymphatic drainage massage, also known as manual lymphatic drainage, is a gentle form of massage that aims to encourage the natural drainage of the lymph, which carries waste products away from the tissues and back toward the heart.',
    minPrice: '65',
    midPrice: "95",
    maxPrice: "125",
    minDuration: 60,
    midDuration: 90,
    maxDuration: 120,
    image: "/services/LYMPHATIC MASSAGE.jpg",
    category: 'Western Massage',
  },
  {
    id: '7',
    name: 'Lomi Lomi Massage',
    description: 'Lomi lomi massage, also known as the “loving hands” massage, is a traditional Hawaiian practice that involves a combination of massage techniques, nut oils, and elements of prayer, breathing, and dance to restore energy and soothe the body.',
    minPrice: '65',
    midPrice: "95",
    maxPrice: "125",
    minDuration: 60,
    midDuration: 90,
    maxDuration: 120,
    image: "/services/LOMI LOMI MASSAGE.jpg",
    category: 'Western Massage',
  },
  {
    id: '8',
    name: 'Relaxing Massage',
    description: 'A relaxation massage is a gentle, full-body therapy that aims to promote relaxation, relieve muscle tension, and improve blood circulation. It typically involves long, smooth, gliding strokes, gentle kneading, and tapping directed towards the heart.',
    minPrice: '60',
    midPrice: "90",
    maxPrice: "120",
    premiumPrice: "180",
    minDuration: 60,
    midDuration: 90,
    maxDuration: 120,
    premiumDuration: 180,
    image: "/services/RELAXING MASSAGE.jpg",
    category: 'Western Massage',
  },
  // Western Massages End

  // Oriental Massages Start
  {
    id: '9',
    name: 'Foot Massage',
    description: 'A foot massage is a therapeutic practice that can provide relaxation and pain relief. It involves applying pressure to specific points on the foot, which is believed to correspond to different organs and systems of the body. ',
    minPrice: '40',
    midPrice: "60",
    maxPrice: "90",
    premiumPrice: "120",
    minDuration: 40,
    midDuration: 60,
    maxDuration: 90,
    premiumDuration: 120,
    image: "/services/FOOT MASSAGE.png",
    category: 'Oriental Massage',
  },
  {
    id: '10',
    name: 'Shaitsu Massage',
    description: 'Shiatsu basically is dry massage without oil. Shiatsu is a form of massage that originated in Japan and utilizes the hands, thumbs, or other body parts to apply direct pressure on various points or channels in the body.',
    minPrice: '60',
    midPrice: "90",
    maxPrice: "120",
    minDuration: 60,
    midDuration: 90,
    maxDuration: 120,
    image: "/services/SHAITSU MASSAGE.jpg",
    category: 'Oriental Massage',
  },
  {
    id: '11',
    name: 'Tui Na Massage',
    description: 'Tui na massage is becoming increasingly popular due to its focus on addressing specific problems and promoting overall well-being. Tui na massage is an ancient Chinese practice that aims to balance the body’s energy and promote self-healing.',
    minPrice: '60',
    midPrice: "90",
    maxPrice: "120",
    minDuration: 60,
    midDuration: 90,
    maxDuration: 120,
    image: "/services/TUI NA MASSAGE.jpg",
    category: 'Oriental Massage',
  },
  {
    id: '12',
    name: 'Ayurveda Massage',
    description: 'Ayurvedic massage is deeply rooted in ancient Indian healing traditions and has its origins in both Nepal and India. It is a holistic approach to wellness that emphasizes balance and harmony between the mind, body, and spirit.',
    minPrice: '65',
    midPrice: "95",
    maxPrice: "130",
    minDuration: 60,
    midDuration: 90,
    maxDuration: 120,
    image: "/services/AYURVEDA MASSAGE.jpg",
    category: 'Oriental Massage',
  },
  {
    id: '13',
    name: 'Thai Oil Massage',
    description: 'Thai massage basically came from Thailand A Thai oil massage is a type of massage therapy that combines the technique of traditional Thai massage with the use of therapeutic oils.',
    minPrice: '60',
    midPrice: "90",
    maxPrice: "120",
    minDuration: 60,
    midDuration: 90,
    maxDuration: 120,
    image: "/services/THAI OIL MASSAGE.jpg",
    category: 'Oriental Massage',
  },
  {
    id: '14',
    name: 'Thai Traditional Massage',
    description: 'Thai traditional massage, also known as Thai yoga massage, is a unique therapeutic technique that has its roots in both Indian Ayurvedic traditions and traditional Thai medicine.',
    minPrice: '60',
    midPrice: "90",
    maxPrice: "120",
    minDuration: 60,
    midDuration: 90,
    maxDuration: 120,
    image: "/services/THAI TRADITIONAL MASSAGE.jpg",
    category: 'Oriental Massage',
  },
  {
    id: '15',
    name: 'Pregnancy Massage',
    description: 'Prenatal massage is widely regarded as safe and beneficial for pregnant women. It can alleviate anxiety, symptoms of depression, muscle aches, and joint pains while enhancing overall prenatal health. ',
    minPrice: '40',
    midPrice: "60",
    maxPrice: "90",
    premiumPrice: "120",
    minDuration: 40,
    midDuration: 60,
    maxDuration: 90,
    premiumDuration: 120,
    image: "/services/PREGNANCY MASSAGE.jpg",
    category: 'Oriental Massage',
  },
  {
    id: '16',
    name: 'Oil Massage',
    description: 'Oil massages offer a luxurious and deeply relaxing. COCONUT • ALMOND • LAVENDER • LEMONGRASS • RASPBERRY',
    minPrice: '65',
    midPrice: "95",
    maxPrice: "125",
    minDuration: 60,
    midDuration: 90,
    maxDuration: 120,
    image: "/services/OIL MASSAGE.jpg",
    category: 'Oriental Massage',
  },
  // Oriental Massages End

  // Special Massages Start
  {
    id: '17',
    name: 'Hot Stone Massage',
    description: 'A hot stone massage is a type of therapy that uses smooth, heated stones, usually made of basalt, to provide warmth and relax the muscles.',
    minPrice: '65',
    midPrice: "95",
    maxPrice: "125",
    premiumPrice: "180",
    minDuration: 60,
    midDuration: 90,
    maxDuration: 120,
    premiumDuration: 180,
    image: "/services/HOT STONE MASSAGE.jpg",
    category: 'Special Massage',
  },
  {
    id: '18',
    name: '4 Hand Massage',
    description: 'A four-hands massage involves two therapists working on one client, often using synchronized moves, providing a unique and relaxing experience.',
    minPrice: '130',
    midPrice: "190",
    maxPrice: "250",
    premiumPrice: "36j0",
    minDuration: 60,
    midDuration: 90,
    maxDuration: 120,
    premiumDuration: 180,
    image: "/services/4 HAND MASSAGE.jpg",
    category: 'Special Massage',
  },
  {
    id: '19',
    name: 'Oriental Facial Massage',
    description: `Oriental facial massage is a holistic practice that combines ancient traditions with modern applications. Face massage including face mask.`,
    minPrice: '40',
    midPrice: "60",
    maxPrice: "90",
    premiumPrice: "120",
    minDuration: 40,
    midDuration: 60,
    maxDuration: 90,
    premiumDuration: 120,
    image: "/services/ORIENTAL FACIAL MASSAGE.jpg",
    category: 'Special Massage',
  },
  {
    id: '20',
    name: 'Candle Massage',
    description: 'A candle massage is a type of massage that incorporates warm, melted wax from specially designed candles. The warm wax, infused with essential oils and natural fragrances.',
    minPrice: '60',
    midPrice: "90",
    maxPrice: "120",
    minDuration: 60,
    midDuration: 90,
    maxDuration: 120,
    image: "/services/CANDLE MASSAGE.webp",
    category: 'Special Massage',
  },
  {
    id: '21',
    name: 'Air Cupping Massage',
    description: 'Fire cupping is an ancient Chinese therapy that uses special cups to create suction on the skin. Traditionally, a flame is used to remove oxygen from the cup before placing it on the skin, creating negative pressure that draws the skin into the cup.',
    minPrice: '60',
    midPrice: "90",
    maxPrice: "120",
    minDuration: 60,
    midDuration: 90,
    maxDuration: 120,
    image: "/services/AIR CUPPING MASSAGE.jpg",
    category: 'Special Massage',
  },
  {
    id: '22',
    name: 'Aroma Therapy Massage',
    description: 'Aromatherapy is a holistic healing practice that utilizes natural plant extracts, known as essential oils, to promote physical, emotional, and mental well-being.',
    minPrice: '60',
    midPrice: "90",
    maxPrice: "120",
    minDuration: 60,
    midDuration: 90,
    maxDuration: 120,
    image: "/services/AROMA THERAPY MASSAGE.png",
    category: 'Special Massage',
  },
  {
    id: '23',
    name: 'Herbal Massage',
    description: 'Herbal massage is a therapeutic technique that combines the benefits of massage with the healing properties of herbs and plant extracts.',
    minPrice: '60',
    midPrice: "90",
    maxPrice: "120",
    minDuration: 60,
    midDuration: 90,
    maxDuration: 120,
    image: "/services/HERBAL MASSAGE.jpg",
    category: 'Special Massage',
  },
  {
    id: '24',
    name: 'Sunburn Massage',
    description: 'Massaging sunburned skin requires a delicate approach to avoid exacerbating discomfort and potential damage. Begin by applying a cool compress or damp cloth to the affected area to reduce inflammation.',
    minPrice: '45',
    midPrice: "65",
    maxPrice: "95",
    minDuration: 40,
    midDuration: 60,
    maxDuration: 90,
    image: "/services/SUNBURN MASSAGE.png",
    category: 'Special Massage',
  },
  {
    id: '25',
    name: 'Tanning Massage',
    description: 'A tanning massage typically involves applying moisturizing or tanning-specific lotions or oils to the skin before, during, or after sun exposure to enhance the tanning process and promote skin hydration.',
    minPrice: '40',
    midPrice: "60",
    maxPrice: "80",
    minDuration: 40,
    midDuration: 60,
    maxDuration: 90,
    image: "/services/TANNING MASSAGE.png",
    category: 'Special Massage',
  },
]

export async function getServices() {
  return mockServices
}

export async function getServiceById(id: string) {
  return mockServices.find((s) => s.id === id) || null
}

export async function getAllServices() {
  return mockServices
}

